### ISSUE TITLE
Cannot find module 'copy-newer' Issue

### ISSUE THREAD

**Issue by jokoho48** [acemod/language-arma-atom#71]
1. Open Any File

**Atom Version**: 1.8.0
**System**: JOKOHO482
**Thrown From**: [language-arma-atom](https://github.com/acemod/language-arma-atom) package, v2.6.0
### Stack Trace

Failed to activate the language-arma-atom package

```
At Cannot find module 'copy-newer'

Error: Cannot find module 'copy-newer'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/jokoho482/.atom/packages/language-arma-atom/index.coffee:2:13)
    at Object.<anonymous> (file:///C:/Users/jokoho482/.atom/packages/language-arma-atom/index.coffee:1:1)
    at Module._compile (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:841:28
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:573:43)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\tokenized-buffer.js:200:27)
    at TokenizedBuffer.module.exports.TokenizedBuffer.reloadGrammar (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\tokenized-buffer.js:211:21)
    at new TokenizedBuffer (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\tokenized-buffer.js:86:14)
    at new DisplayBuffer (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\display-buffer.js:91:32)
    at new TextEditor (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:149:30)
    at Workspace.module.exports.Workspace.buildTextEditor (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:623:14)
    at Workspace.buildTextEditor (C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:60:52)
    at C:\Users\jokoho482\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:594:26
    at process._tickCallback (node.js:392:9)
```
### Commands

```
     -1:36 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:33.7.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:31.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:28 tree-view:add-folder (div.header.list-item)
  3x -1:26.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:14.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:09.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:58.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:57.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.6.0 tree-view:move (span.name.icon.icon-file-text)
     -0:52.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini.is-focused)
     -0:50.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  },
  "language-arma-atom": {
    "autocomplete": {}
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax-dark, v0.2.5
atom-material-ui, v1.2.13
highlight-selected, v0.11.2
keyboard-localization, v1.4.18
language-arma-atom, v2.6.0
minimap, v4.24.7
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
project-plus, v0.9.0

# Dev
No dev packages
```

**Comment by jonpas** [comment]
@jokoho48 Are you using the development version of language-arma-atom cloned from GitHub?

**Comment by jokoho48** [comment]
yes

**Comment by thojkooi** [comment]
You are missing the dependencies - run `npm i` to install them. Do this in the cloned directory. Let me know if you need some help with that.

**Comment by jonpas** [comment]
What @Glowbal said, development versions of packages do not install dependencies automatically, stable published version does.
