### ISSUE TITLE
Failed to load the Language-Arma Atom Package Settings

### ISSUE THREAD

**Issue by dixonbegay** [acemod/language-arma-atom#73]
Receiving this error after recent update
### Steps to reproduce
1. Start Atom With Language-Arma-Atom installed
2. Error should pop up

**Atom Version**: 1.9.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-arma-atom](https://github.com/acemod/language-arma-atom) package, v2.6.1
### Stack Trace

Failed to load the language-arma-atom package settings

```
At C:\Users\dixon\.atom\packages\language-arma-atom\settings\language-sqf-native-commands.json: Unexpected end of input in C:\Users\dixon\.atom\packages\language-arma-atom\settings\language-sqf-native-commands.json

SyntaxError: C:\Users\dixon\.atom\packages\language-arma-atom\settings\language-sqf-native-commands.json: Unexpected end of input
    at Object.parse (native)
    at parseObject (C:\Users\dixon\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\season\lib\cson.js:54:19)
    at parseContents (C:\Users\dixon\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\season\lib\cson.js:102:16)
    at C:\Users\dixon\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\season\lib\cson.js:204:20
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
  at C:\Users\dixon\.atom\packages\language-arma-atom\settings\language-sqf-native-commands.json:1:1
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-django"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
django-atom, v0.2.4 (inactive)
django-templates, v0.5.0 (inactive)
language-arma-atom, v2.6.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

`

**Comment by thojkooi** [comment]
Thanks, will look at this later today.

**Comment by dixonbegay** [comment]
Updated to **Atom Version**: 1.10.0 and the issue still persists.

**Comment by jonpas** [comment]
@dixon13 Did you install the package from source or through package manager? If you do it from source then you must install `copy-newer` package manually, if through package manager it is installed automatically.

The only other thing I can see going wrong is some incompatibility with some other package.

**Comment by dixonbegay** [comment]
I installed using the package manager. I'm going to do a full reinstall of the package and disable/uninstall my other packages. Will keep you guys updated as to what happens.

**Comment by dixonbegay** [comment]
Did fresh install and seems to be working great. Idk what happen. Closing.

**Comment by jonpas** [comment]
Glad you resolved it!
